ALTER TABLE `dongjing`.`securityinfo`
DROP COLUMN `dcNumber`,
DROP COLUMN `dcCategroy`,
DROP COLUMN `farmerTrainee`,
DROP COLUMN `farmerNumber`,
DROP COLUMN `employeeTrainee`,
DROP COLUMN `employeeNumber`,
DROP COLUMN `traningValidDate`,
DROP COLUMN `mgnCertValidDate`,
DROP COLUMN `pipeLength`,
DROP COLUMN `pressurePipe`,
DROP COLUMN `safeNo`,
DROP COLUMN `isPassStandard`,
DROP COLUMN `fireControlCertificateDate`,
DROP COLUMN `fireControlMembers`,
DROP COLUMN `safeMemberParttime`,
DROP COLUMN `safeMemberFullTime`,
DROP COLUMN `safeManageOrg`,
DROP COLUMN `assetDate`,
DROP COLUMN `safeLevel`,
DROP COLUMN `isContractedCompany`,
DROP COLUMN `safeCertificateValidDate`,
DROP COLUMN `reportDepartment`,
DROP COLUMN `major`,
DROP COLUMN `economyEntityID`,
CHANGE COLUMN `dirtyWaterMgn` `isDirtyWaterMgn` BIT(1) NULL DEFAULT NULL ,
CHANGE COLUMN `isDCProduceOrg` `isDCProduceOrg` BIT(1) NULL DEFAULT NULL AFTER `isDirtyWaterMgn`,
CHANGE COLUMN `dcTypeID` `dcTypeID` BIGINT(20) NULL DEFAULT NULL AFTER `isDCProduceOrg`,
ADD COLUMN `isEmergencyPassStandard` VARCHAR(45) NULL DEFAULT NULL AFTER `name`,
ADD COLUMN `isSecurityStandardPassed` BIT(1) NULL DEFAULT NULL AFTER `isEmergencyPassStandard`,
ADD COLUMN `fireController` VARCHAR(45) NULL DEFAULT NULL AFTER `isSecurityStandardPassed`,
ADD COLUMN `companyHead` VARCHAR(45) NULL DEFAULT NULL AFTER `specialOthers`;
