ALTER TABLE `dongjing`.`company` 
ADD COLUMN `isR` BIT NULL AFTER `currencyID`,
ADD COLUMN `isS` BIT NULL AFTER `isR`,
ADD COLUMN `isT` BIT NULL AFTER `isS`,
ADD COLUMN `isU` BIT NULL AFTER `isT`,
ADD COLUMN `isV` BIT NULL AFTER `isU`,
ADD COLUMN `isW` BIT NULL AFTER `isV`,
ADD COLUMN `rDate` DATE NULL AFTER `isW`,
ADD COLUMN `sDate` DATE NULL AFTER `rDate`,
ADD COLUMN `tDate` DATE NULL AFTER `sDate`,
ADD COLUMN `uDate` DATE NULL AFTER `tDate`,
ADD COLUMN `vDate` DATE NULL AFTER `uDate`,
ADD COLUMN `wDate` DATE NULL AFTER `vDate`;


