ALTER TABLE `dongjing`.`company` 
CHANGE COLUMN `usageArea` `usageArea` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `rentArea` `rentArea` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `spareArea` `spareArea` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `companyArea` `companyArea` DOUBLE NULL DEFAULT NULL ;
