-- MySQL Script generated by MySQL Workbench
-- 08/25/14 23:21:51
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dongjing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dongjing` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `dongjing` ;

-- -----------------------------------------------------
-- Table `companyContact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `companyContact` ;

CREATE TABLE IF NOT EXISTS `companyContact` (
  `contactID` BIGINT NOT NULL AUTO_INCREMENT,
  `genderID` BIGINT NULL,
  `fullName` VARCHAR(100) NULL,
  `phone` VARCHAR(255) NULL,
  `cellPhone` VARCHAR(255) NULL,
  `emailAddress` VARCHAR(100) NULL,
  `idCard` VARCHAR(45) NULL,
  `postalCode` VARCHAR(20) NULL,
  `address` VARCHAR(1000) NULL,
  `fax` VARCHAR(20) NULL,
  PRIMARY KEY (`contactID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company` ;

CREATE TABLE IF NOT EXISTS `company` (
  `companyID` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `companyNo` VARCHAR(45) NULL,
  `commercialNo` VARCHAR(45) NULL,
  `organizationCode` VARCHAR(255) NULL,
  `docNo` VARCHAR(45) NULL,
  `registerAddress` VARCHAR(2000) NULL,
  `operateAddress` VARCHAR(2000) NULL,
  `registerAsset` INT NULL,
  `branchNumber` INT NULL,
  `regionID` BIGINT NULL,
  `commercialStatusID` BIGINT NULL,
  `taxStatusID` BIGINT NULL,
  `economyEntityID` BIGINT NULL,
  `economyNatureID` BIGINT NULL,
  `industryType` VARCHAR(100) NULL,
  `collectMethodID` BIGINT NULL,
  `affiliateRegionID` BIGINT NULL,
  `taxNatureID` BIGINT NULL,
  `taxTypeID` BIGINT NULL,
  `establishDate` DATE NULL,
  `materialDate` DATE NULL,
  `handleDate` DATE NULL,
  `issueDate` DATE NULL,
  `moveInDate` DATE NULL,
  `transferDate` DATE NULL,
  `taxCancellation` DATE NULL,
  `commercialCancellation` DATE NULL,
  `taxCollector` VARCHAR(45) NULL,
  `merchat` VARCHAR(255) NULL,
  `affliateMerchat` VARCHAR(1000) NULL,
  `isEDeclaration` BIT NULL,
  `isReceiptBought` BIT NULL,
  `isNormalTaxer` BIT NULL,
  `certificationNo` VARCHAR(100) NULL,
  `companyIdentifier` VARCHAR(100) NULL,
  `infoCardNo` VARCHAR(100) NULL,
  `operationStartYear` DATE NULL,
  `operationEndYear` DATE NULL,
  `validStartYear` DATE NULL,
  `validEndYear` DATE NULL,
  `operationMethod` VARCHAR(255) NULL,
  `normalTaxerAuthDate` DATE NULL,
  `operationScope` VARCHAR(2000) NULL,
  `remarkables` VARCHAR(2000) NULL,
  `unifiedCode` VARCHAR(100) NULL,
  `taxMngCode` VARCHAR(100) NULL,
  `taxRegNo` VARCHAR(100) NULL,
  `purchasedBookNo` VARCHAR(100) NULL,
  `bank` VARCHAR(255) NULL,
  `bankAccount` VARCHAR(255) NULL,
  `taxAccount` VARCHAR(255) NULL,
  `ownerContactID` BIGINT NULL,
  `otherContactID` BIGINT NULL,
  `shareholderContactID` BIGINT NULL,
  `shareRatio` VARCHAR(100) NULL,
  `branches` VARCHAR(500) NULL,
  `taxOrgID` BIGINT NULL,
  `isA` BIT NULL,
  `isB` BIT NULL,
  `isC` BIT NULL,
  `isD` BIT NULL,
  `isE` BIT NULL,
  `isF` BIT NULL,
  `isG` BIT NULL,
  `isH` BIT NULL,
  `isI` BIT NULL,
  `isJ` BIT NULL,
  `isK` BIT NULL,
  `isL` BIT NULL,
  `isM` BIT NULL,
  `isN` BIT NULL,
  `aDate` DATE NULL,
  `bDate` DATE NULL,
  `cDate` DATE NULL,
  `dDate` DATE NULL,
  `eDate` DATE NULL,
  `fDate` DATE NULL,
  `gDate` DATE NULL,
  `hDate` DATE NULL,
  `iDate` DATE NULL,
  `jDate` DATE NULL,
  `kDate` DATE NULL,
  `lDate` DATE NULL,
  `mDate` DATE NULL,
  `nDate` DATE NULL,
  `partyName` VARCHAR(100) NULL,
  `partyLeader` VARCHAR(100) NULL,
  `area` INT NULL,
  `ownership` VARCHAR(100) NULL,
  `sleepingRoomNumbers` INT NULL,
  `usageArea` INT NULL,
  `rentArea` INT NULL,
  `spareArea` INT NULL,
  `companyArea` INT NULL,
  `localEmployeeNumber` INT NULL,
  `employeeNumber` INT NULL,
  `landUsageID` BIGINT NULL,
  `factoryArea` DOUBLE NULL,
  `factoryUsageArea` DOUBLE NULL,
  `factoryRentArea` DOUBLE NULL,
  `factoryControlArea` DOUBLE NULL,
  `factoryActualArea` DOUBLE NULL,
  `isRent` TINYINT(1) NULL,
  PRIMARY KEY (`companyID`),
  INDEX `FK_companyContact_ownerContactID_idx` (`ownerContactID` ASC),
  UNIQUE INDEX `IDX_company_name_UNIQUE` (`name` ASC),
  INDEX `FK_companyContact_shareholderContactID` (`otherContactID` ASC),
  INDEX `FK_companyContact_otherContactID` (`shareholderContactID` ASC),
  CONSTRAINT `FK_companyContact_ownerContactID`
    FOREIGN KEY (`ownerContactID`)
    REFERENCES `companyContact` (`contactID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_companyContact_shareholderContactID`
    FOREIGN KEY (`otherContactID`)
    REFERENCES `companyContact` (`contactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_companyContact_otherContactID`
    FOREIGN KEY (`shareholderContactID`)
    REFERENCES `companyContact` (`contactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `companySaleTaxData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `companySaleTaxData` ;

CREATE TABLE IF NOT EXISTS `companySaleTaxData` (
  `year` INT NOT NULL,
  `month` INT NOT NULL,
  `companyID` BIGINT NOT NULL,
  `industry` VARCHAR(100) NOT NULL,
  `accSales` DOUBLE NULL,
  `sales` DOUBLE NULL,
  `vat` DOUBLE NULL,
  `operateTax` DOUBLE NULL,
  `expenseTax` DOUBLE NULL,
  `domesticIncomingTax` DOUBLE NULL,
  `foreignIncomingTax` DOUBLE NULL,
  `housingTax` DOUBLE NULL,
  `stampTax` DOUBLE NULL,
  `trafficTax` DOUBLE NULL,
  `landVAT` DOUBLE NULL,
  `landUseTax` DOUBLE NULL,
  `personalIncomingTax` DOUBLE NULL,
  `constructionTax` DOUBLE NULL,
  `veichleTax` DOUBLE NULL,
  `riverTax` DOUBLE NULL,
  `educationTax` DOUBLE NULL,
  `cultureTax` DOUBLE NULL,
  `otherTax` DOUBLE NULL,
  `economyNatureID` BIGINT NULL,
  `economyEntityID` BIGINT NULL,
  `taxOrgID` BIGINT NULL,
  `affiliateRegionID` BIGINT NULL,
  `isMYC` BIT NULL,
  PRIMARY KEY (`year`, `month`, `companyID`),
  INDEX `fk_companySaleTaxData_company1_idx` (`companyID` ASC),
  CONSTRAINT `fk_companySaleTaxData_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contacts` ;

CREATE TABLE IF NOT EXISTS `contacts` (
  `contactID` BIGINT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `cellPhone` VARCHAR(45) NULL,
  `emailAddress` VARCHAR(100) NULL,
  `title` VARCHAR(100) NULL,
  `department` VARCHAR(45) NULL,
  PRIMARY KEY (`contactID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `userID` BIGINT NOT NULL AUTO_INCREMENT,
  `userStatusID` BIGINT NOT NULL,
  `contactID` BIGINT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `lastLoginDate` DATETIME NULL,
  `createdDate` DATETIME NOT NULL,
  PRIMARY KEY (`userID`, `contactID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_users_contacts1_idx` (`contactID` ASC),
  CONSTRAINT `fk_users_contacts1`
    FOREIGN KEY (`contactID`)
    REFERENCES `contacts` (`contactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

CREATE TABLE IF NOT EXISTS `roles` (
  `roleID` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`roleID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rights` ;

CREATE TABLE IF NOT EXISTS `rights` (
  `rightID` BIGINT NOT NULL AUTO_INCREMENT,
  `parentRightID` BIGINT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rightID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role_right`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_right` ;

CREATE TABLE IF NOT EXISTS `role_right` (
  `roleID` BIGINT NOT NULL,
  `rightID` BIGINT NOT NULL,
  PRIMARY KEY (`roleID`, `rightID`),
  INDEX `fk_roles_has_rights_rights1_idx` (`rightID` ASC),
  INDEX `fk_roles_has_rights_roles1_idx` (`roleID` ASC),
  CONSTRAINT `fk_roles_has_rights_roles1`
    FOREIGN KEY (`roleID`)
    REFERENCES `roles` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_rights_rights1`
    FOREIGN KEY (`rightID`)
    REFERENCES `rights` (`rightID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role` ;

CREATE TABLE IF NOT EXISTS `user_role` (
  `userID` BIGINT NOT NULL,
  `roleID` BIGINT NOT NULL,
  PRIMARY KEY (`userID`, `roleID`),
  INDEX `fk_users_has_roles_roles1_idx` (`roleID` ASC),
  INDEX `fk_users_has_roles_users1_idx` (`userID` ASC),
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`roleID`)
    REFERENCES `roles` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysEnums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysEnums` ;

CREATE TABLE IF NOT EXISTS `sysEnums` (
  `sysEnumID` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `sequence` INT NOT NULL,
  PRIMARY KEY (`sysEnumID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monthlyStatisticData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monthlyStatisticData` ;

CREATE TABLE IF NOT EXISTS `monthlyStatisticData` (
  `year` INT NOT NULL,
  `month` INT NOT NULL,
  `merchantIndustry` INT NULL,
  `merchantCommercial` INT NULL,
  `merchantService` INT NULL,
  `merchantConstruct` INT NULL,
  `merchantHouseHolding` INT NULL,
  `merchantSignOffCompanies` INT NULL,
  `regAssetsIndustry` INT NULL,
  `regAssetsCommercial` INT NULL,
  `regAssetsService` INT NULL,
  `regAssetsConstruct` INT NULL,
  `regAssetsHouseholding` INT NULL,
  `vat` INT NULL,
  `operateTax` INT NULL,
  `incomingTax` INT NULL,
  `constructTax` INT NULL,
  `otherTax` INT NULL,
  `salesTotal` INT NULL,
  `privateCompanyVAT` DOUBLE NULL,
  `privateCompanyOperateTax` DOUBLE NULL,
  `privateCompanyIncomingTax` DOUBLE NULL,
  `privateCompanyPersonalIncomingTax` DOUBLE NULL,
  `privateCompanyConstructTax` DOUBLE NULL,
  `privateCompanyOtherTax` DOUBLE NULL,
  `publicCompanyVAT` DOUBLE NULL,
  `publicCompanyOperateTax` DOUBLE NULL,
  `publicCompanyIncomingTax` DOUBLE NULL,
  `publicCompanyPersonalIncomingTax` DOUBLE NULL,
  `publicCompanyConstructTax` DOUBLE NULL,
  `publicCompanyOtherTax` DOUBLE NULL,
  `groupCompanyVAT` DOUBLE NULL,
  `groupCompanyOperateTax` DOUBLE NULL,
  `groupCompanyIncomingTax` DOUBLE NULL,
  `groupCompanyPersonalIncomingTax` DOUBLE NULL,
  `groupCompanyConstructTax` DOUBLE NULL,
  `groupCompanyOtherTax` DOUBLE NULL,
  `industryVAT` DOUBLE NULL,
  `commercialVAT` DOUBLE NULL,
  `constructVAT` DOUBLE NULL,
  `serviceVAT` DOUBLE NULL,
  `houseHoldingVAT` DOUBLE NULL,
  `industryOperateTax` DOUBLE NULL,
  `commercialOperateTax` DOUBLE NULL,
  `constructOperateTax` DOUBLE NULL,
  `serviceOperateTax` DOUBLE NULL,
  `houseHoldingOperateTax` DOUBLE NULL,
  `industryIncomingTax` DOUBLE NULL,
  `commercialIncomingTax` DOUBLE NULL,
  `constructIncomingTax` DOUBLE NULL,
  `serviceIncomingTax` DOUBLE NULL,
  `houseHoldingIncomingTax` DOUBLE NULL,
  `industryPersonalIncomingTax` DOUBLE NULL,
  `commercialPersonalIncomingTax` DOUBLE NULL,
  `constructPersonalIncomingTax` DOUBLE NULL,
  `servicePersonalIncomingTax` DOUBLE NULL,
  `houseHoldingPersonalIncomingTax` DOUBLE NULL,
  `industryConstructTax` DOUBLE NULL,
  `commercialConstructTax` DOUBLE NULL,
  `constructConstructTax` DOUBLE NULL,
  `serviceConstructTax` DOUBLE NULL,
  `houseHoldingConstructTax` DOUBLE NULL,
  `industryOtherTax` DOUBLE NULL,
  `commercialOtherTax` DOUBLE NULL,
  `constructOtherTax` DOUBLE NULL,
  `serviceOtherTax` DOUBLE NULL,
  `houseHoldingOtherTax` DOUBLE NULL,
  `industrySale` DOUBLE NULL,
  `commercialSale` DOUBLE NULL,
  `constructSale` DOUBLE NULL,
  `serviceSale` DOUBLE NULL,
  `houseHoldingSale` DOUBLE NULL,
  PRIMARY KEY (`year`, `month`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `projectID` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `statusID` BIGINT NOT NULL,
  `isCommercial` BIT NULL,
  `area` DOUBLE NULL,
  `constructionArea` DOUBLE NULL,
  `product` VARCHAR(100) NULL,
  `domesticInvestment` DOUBLE NULL,
  `foreignInvestment` DOUBLE NULL,
  `fixInvestment` DOUBLE NULL,
  `totalInvestment` DOUBLE NULL,
  `sales` DOUBLE NULL,
  `profit` DOUBLE NULL,
  `tax` DOUBLE NULL,
  `auditPassDate` DATE NULL,
  `constructTypeID` BIGINT NULL,
  `actualArea` DOUBLE NULL,
  `numberOfBuilding` VARCHAR(200) NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `produceDate` DATE NULL,
  `progress` VARCHAR(100) NULL,
  `problem` VARCHAR(200) NULL,
  `contactor` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `fax` VARCHAR(45) NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`projectID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `member` ;

CREATE TABLE IF NOT EXISTS `member` (
  `memberID` BIGINT NOT NULL AUTO_INCREMENT,
  `companyID` BIGINT NOT NULL,
  `name` VARCHAR(100) NULL COMMENT '	',
  `position` VARCHAR(100) NULL,
  `produceMethod` VARCHAR(100) NULL,
  `idTypeID` BIGINT NULL,
  `idNo` VARCHAR(45) NULL,
  `certificate` VARCHAR(100) NULL,
  PRIMARY KEY (`memberID`),
  INDEX `fk_member_company1_idx` (`companyID` ASC),
  CONSTRAINT `fk_member_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `partyMember`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `partyMember` ;

CREATE TABLE IF NOT EXISTS `partyMember` (
  `memberID` BIGINT NOT NULL AUTO_INCREMENT,
  `companyID` BIGINT NOT NULL,
  `name` VARCHAR(100) NULL,
  `genderID` BIGINT NULL,
  `education` VARCHAR(100) NULL,
  PRIMARY KEY (`memberID`),
  INDEX `fk_partyMember_company1_idx` (`companyID` ASC),
  CONSTRAINT `fk_partyMember_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `securityInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securityInfo` ;

CREATE TABLE IF NOT EXISTS `securityInfo` (
  `securityInfoID` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `economyEntityID` BIGINT NULL,
  `major` VARCHAR(45) NULL,
  `reportDepartment` VARCHAR(45) NULL,
  `safeCertificateValidDate` DATE NULL,
  `isContractedCompany` BIT NULL,
  `safeLevel` VARCHAR(45) NULL,
  `assetDate` DATE NULL,
  `safeManageOrg` VARCHAR(45) NULL,
  `safeMemberFullTime` INT NULL,
  `safeMemberParttime` INT NULL,
  `fireControlMembers` INT NULL,
  `fireControlCertificateDate` DATE NULL,
  `isEnvAssessPass` BIT NULL,
  `dirtyWaterMgn` VARCHAR(45) NULL,
  `isPassStandard` BIT NULL,
  `safeNo` VARCHAR(45) NULL,
  `elevator` INT NULL,
  `crane` INT NULL,
  `recreationFacility` INT NULL,
  `indoorFacility` INT NULL,
  `boiler` INT NULL,
  `pressureContainer` INT NULL,
  `pressurePipe` INT NULL,
  `pipeLength` INT NULL,
  `specialOthers` INT NULL,
  `mgnCertValidDate` DATE NULL,
  `safeManagerName` VARCHAR(45) NULL,
  `traningValidDate` DATE NULL,
  `electronist` INT NULL,
  `boilist` INT NULL,
  `electrowelder` INT NULL,
  `climbConstructor` INT NULL,
  `forklifter` INT NULL,
  `driver` INT NULL,
  `elevateOperator` INT NULL,
  `trainingOther` INT NULL,
  `employeeNumber` INT NULL,
  `employeeTrainee` INT NULL,
  `farmerNumber` INT NULL,
  `farmerTrainee` INT NULL,
  `isDCProduceOrg` BIT NULL,
  `dcTypeID` BIGINT NULL,
  `dcCategroy` VARCHAR(45) NULL,
  `dcNumber` INT NULL,
  PRIMARY KEY (`securityInfoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agricultureInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agricultureInfo` ;

CREATE TABLE IF NOT EXISTS `agricultureInfo` (
  `agriID` BIGINT NOT NULL AUTO_INCREMENT,
  `farmerName` VARCHAR(100) NULL,
  `contactNumber` VARCHAR(45) NULL,
  `area` INT NULL,
  `address` VARCHAR(200) NULL,
  `paddyArea` INT NULL,
  `wheatArea` INT NULL,
  `greenArea` INT NULL,
  `assartArea` INT NULL,
  PRIMARY KEY (`agriID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commercialArea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commercialArea` ;

CREATE TABLE IF NOT EXISTS `commercialArea` (
  `commercialAreaID` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `typeID` BIGINT NOT NULL,
  `scope` VARCHAR(255) NULL,
  `residentialArea` VARCHAR(255) NULL,
  `residentNumbers` VARCHAR(45) NULL,
  `storePopulation` VARCHAR(45) NULL,
  `ownerEduProvinceAge` VARCHAR(500) NULL,
  `start` VARCHAR(100) NULL,
  `end` VARCHAR(100) NULL,
  `length` VARCHAR(100) NULL,
  `totalArea` VARCHAR(45) NULL,
  `ownArea` VARCHAR(45) NULL,
  `rentArea` VARCHAR(45) NULL,
  `spareArea` VARCHAR(45) NULL,
  `constructDescription` VARCHAR(255) NULL,
  `retailNumber` INT NULL,
  `retailMainBrands` VARCHAR(100) NULL,
  `caterNumber` INT NULL,
  `caterMainBrands` VARCHAR(100) NULL,
  `entertainNumber` INT NULL,
  `entertainMainBrands` VARCHAR(100) NULL,
  `serviceNumber` INT NULL,
  `serviceMainBrands` VARCHAR(100) NULL,
  `farmNumber` INT NULL,
  `farmMainBrands` VARCHAR(100) NULL,
  `otherNumber` INT NULL,
  `otherMainBrands` VARCHAR(100) NULL,
  `annualIncoming` VARCHAR(45) NULL,
  `annualTax` VARCHAR(45) NULL,
  `comment` VARCHAR(255) NULL,
  `totalCommercialEquipment` VARCHAR(45) NULL,
  PRIMARY KEY (`commercialAreaID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store` ;

CREATE TABLE IF NOT EXISTS `store` (
  `storeID` BIGINT NOT NULL AUTO_INCREMENT,
  `commercialAreaID` BIGINT NULL,
  `name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `employeeNumber` INT NULL,
  `totalArea` VARCHAR(45) NULL,
  `ownArea` VARCHAR(45) NULL,
  `rentArea` VARCHAR(45) NULL,
  `spareArea` VARCHAR(45) NULL,
  `industryCode` VARCHAR(45) NULL,
  `mainBrands` VARCHAR(255) NULL,
  `annualIncoming` VARCHAR(45) NULL,
  `annualTax` VARCHAR(45) NULL,
  `comment` VARCHAR(500) NULL,
  PRIMARY KEY (`storeID`),
  INDEX `fk_store_commercialArea1_idx` (`commercialAreaID` ASC),
  CONSTRAINT `fk_store_commercialArea1`
    FOREIGN KEY (`commercialAreaID`)
    REFERENCES `commercialArea` (`commercialAreaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relatedCompany`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relatedCompany` ;

CREATE TABLE IF NOT EXISTS `relatedCompany` (
  `projectID` BIGINT NOT NULL,
  `companyID` BIGINT NOT NULL,
  INDEX `fk_relatedCompany_project1_idx` (`projectID` ASC),
  INDEX `fk_relatedCompany_company1_idx` (`companyID` ASC),
  PRIMARY KEY (`projectID`, `companyID`),
  CONSTRAINT `fk_relatedCompany_project1`
    FOREIGN KEY (`projectID`)
    REFERENCES `project` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relatedCompany_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `annualOutput`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `annualOutput` ;

CREATE TABLE IF NOT EXISTS `annualOutput` (
  `outputID` BIGINT NOT NULL AUTO_INCREMENT,
  `companyID` BIGINT NOT NULL,
  `year` INT NULL,
  `output` DOUBLE NULL,
  `profit` DOUBLE NULL,
  PRIMARY KEY (`outputID`),
  INDEX `fk_annualOutput_company1_idx` (`companyID` ASC),
  CONSTRAINT `fk_annualOutput_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `natureShareHolder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natureShareHolder` ;

CREATE TABLE IF NOT EXISTS `natureShareHolder` (
  `contactID` BIGINT NOT NULL AUTO_INCREMENT,
  `companyID` BIGINT NOT NULL,
  `fullName` VARCHAR(255) NULL,
  `cellPhone` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `emailAddress` VARCHAR(100) NULL,
  `idCard` VARCHAR(45) NULL,
  `address` VARCHAR(1000) NULL,
  `fax` VARCHAR(20) NULL,
  `shareRatio` VARCHAR(45) NULL,
  PRIMARY KEY (`contactID`),
  INDEX `fk_natureShareHolder_company1_idx` (`companyID` ASC),
  CONSTRAINT `fk_natureShareHolder_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `companyShareholder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `companyShareholder` ;

CREATE TABLE IF NOT EXISTS `companyShareholder` (
  `contactID` BIGINT NOT NULL AUTO_INCREMENT,
  `companyID` BIGINT NOT NULL,
  `fullName` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `idType` VARCHAR(45) NULL,
  `idCard` VARCHAR(45) NULL,
  `address` VARCHAR(1000) NULL,
  `shareRatio` VARCHAR(45) NULL,
  PRIMARY KEY (`contactID`),
  INDEX `fk_natureShareHolder_company1_idx` (`companyID` ASC),
  CONSTRAINT `fk_natureShareHolder_company10`
    FOREIGN KEY (`companyID`)
    REFERENCES `company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentRelation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentRelation` ;

CREATE TABLE IF NOT EXISTS `rentRelation` (
  `relationID` BIGINT NOT NULL AUTO_INCREMENT,
  `rentorID` BIGINT NULL,
  `renteeID` BIGINT NULL,
  `nonDJCompany` VARCHAR(255) NULL,
  `area` DOUBLE NULL,
  `address` VARCHAR(500) NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`relationID`),
  INDEX `IDX_RENTEE_ID` (`renteeID` ASC),
  INDEX `IDX_RENTOR_ID` (`rentorID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
